# Generated by Django 6.0.6 on 2026-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmemo', '0005_memo_created_at_memo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='execution_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
