# Generated by Django 6.0.6 on 2026-08-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmemo', '0006_memo_execution_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='execution_output',
        ),
    ]
